// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UsersTasks.Models;

namespace UsersTasks.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("UsersTasks.Models.Objective", b =>
                {
                    b.Property<int>("ObjectiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DirectorId")
                        .HasColumnType("integer");

                    b.Property<int>("ExecutorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("StatusObjective")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ObjectiveId");

                    b.HasIndex("DirectorId");

                    b.HasIndex("ExecutorId");

                    b.ToTable("Objectives");

                    b.HasData(
                        new
                        {
                            ObjectiveId = 1,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task1",
                            DirectorId = 3,
                            ExecutorId = 2,
                            Name = "Task1",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2020, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 2,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task2",
                            DirectorId = 3,
                            ExecutorId = 2,
                            Name = "Task2",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2020, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 3,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task3",
                            DirectorId = 3,
                            ExecutorId = 2,
                            Name = "Task3",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2020, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 4,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task4",
                            DirectorId = 3,
                            ExecutorId = 2,
                            Name = "Task4",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2020, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 5,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task5",
                            DirectorId = 3,
                            ExecutorId = 2,
                            Name = "Task5",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2020, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 6,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task6",
                            DirectorId = 3,
                            ExecutorId = 2,
                            Name = "Task6",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2021, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 7,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task7",
                            DirectorId = 5,
                            ExecutorId = 4,
                            Name = "Task7",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 8,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task8",
                            DirectorId = 5,
                            ExecutorId = 4,
                            Name = "Task8",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2020, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 9,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task9",
                            DirectorId = 5,
                            ExecutorId = 4,
                            Name = "Task9",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 10,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task10",
                            DirectorId = 5,
                            ExecutorId = 4,
                            Name = "Task10",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2021, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 11,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task11",
                            DirectorId = 5,
                            ExecutorId = 4,
                            Name = "Task11",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2022, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 12,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task12",
                            DirectorId = 5,
                            ExecutorId = 4,
                            Name = "Task12",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2020, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 13,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task13",
                            DirectorId = 2,
                            ExecutorId = 1,
                            Name = "Task13",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2022, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 14,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task14",
                            DirectorId = 2,
                            ExecutorId = 1,
                            Name = "Task14",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2021, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 15,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task15",
                            DirectorId = 2,
                            ExecutorId = 1,
                            Name = "Task15",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2021, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 16,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task16",
                            DirectorId = 2,
                            ExecutorId = 1,
                            Name = "Task16",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2020, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 17,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task17",
                            DirectorId = 2,
                            ExecutorId = 1,
                            Name = "Task17",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2022, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 18,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task18",
                            DirectorId = 2,
                            ExecutorId = 1,
                            Name = "Task18",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2022, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 19,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task19",
                            DirectorId = 2,
                            ExecutorId = 1,
                            Name = "Task19",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2022, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 20,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task20",
                            DirectorId = 1,
                            ExecutorId = 3,
                            Name = "Task20",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2021, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 21,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task21",
                            DirectorId = 1,
                            ExecutorId = 3,
                            Name = "Task21",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2021, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 22,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task22",
                            DirectorId = 1,
                            ExecutorId = 3,
                            Name = "Task22",
                            StatusObjective = 0,
                            UpdatedTime = new DateTime(2021, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 23,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task23",
                            DirectorId = 1,
                            ExecutorId = 3,
                            Name = "Task23",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2021, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ObjectiveId = 24,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is Task24",
                            DirectorId = 1,
                            ExecutorId = 3,
                            Name = "Task24",
                            StatusObjective = 1,
                            UpdatedTime = new DateTime(2021, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("UsersTasks.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tom",
                            Status = 1,
                            Surname = "Cruise",
                            UpdatedTime = new DateTime(2020, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice",
                            Status = 1,
                            Surname = "Cooper",
                            UpdatedTime = new DateTime(2020, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 3,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James",
                            Status = 1,
                            Surname = "Woods",
                            UpdatedTime = new DateTime(2020, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 4,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Isaac",
                            Status = 1,
                            Surname = "Clarke",
                            UpdatedTime = new DateTime(2020, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 5,
                            CreatedTime = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James",
                            Status = 1,
                            Surname = "Deen",
                            UpdatedTime = new DateTime(2020, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("UsersTasks.Models.Objective", b =>
                {
                    b.HasOne("UsersTasks.Models.User", "Director")
                        .WithMany("ObjectivesDirector")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UsersTasks.Models.User", "Executor")
                        .WithMany("ObjectivesExecutor")
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Executor");
                });

            modelBuilder.Entity("UsersTasks.Models.User", b =>
                {
                    b.Navigation("ObjectivesDirector");

                    b.Navigation("ObjectivesExecutor");
                });
#pragma warning restore 612, 618
        }
    }
}
